### ISSUE TITLE
Gzip content decompression

### ISSUE THREAD

**Issue by sardaukar** [marcyb/rmitm#1]
Hello!

I have some dumps that I'm using your gem to read, and for some the content is in binary (which I assume is Gzip-compressed). I've tried decompressing them with:

<pre>
def gunzip(data)
  io = StringIO.new(data, "rb:ISO-8859-1")
  gz = Zlib::GzipReader.new(io)
  gz.read
end
</pre>

But I keep getting:

<pre>
Zlib::GzipFile::Error: not in gzip format
</pre>

Any thoughts?

**Comment by sardaukar** [comment]
Btw, saving them to a file and then doing <pre>cat file | gunzip </pre> works :/

**Comment by marcyb** [comment]
Hi Bruno,

Thanks for the mail. If you provide a few more details of how you are using
my gem then I can take a look, I actually suspect that the problem may well
be within the libmproxy library which my code uses to read from dumps.

Cheers

Marc

On 15 August 2014 19:31, Bruno Antunes notifications@github.com wrote:

> Btw, saving them to a file and then doing
> 
> cat file | gunzip
> 
> works :/
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcyb/rmitm/issues/1#issuecomment-52341684.

## 

 http://www.itv.com

http://www.itv.com
http://www.itv.com

ITV plc (Registration No. 4967001) (ITV) is incorporated in England and 
Wales with its registered office at The London Television Centre, Upper 
Ground, London SE1 9LT. Please visit the official ITV website at www.itv.com 
for the latest company news.

The contents of this email and any attachments are confidential, may be 
privileged, may be subject to copyright and are intended solely for the use 
of the individual to whom they are addressed. If you have received this 
email and you are not the intended recipient please notifypostmaster@itv.com 
and delete this email and you are notified that disclosing, copying, 
distributing or taking any action in reliance on the contents of this email 
are strictly prohibited.

Although ITV routinely screens for viruses, recipients should scan this 
email and any attachments for viruses. ITV makes no representation or 
warranty that this email or any of its attachments is free of viruses or 
defects and does not accept any responsibility for any damage caused by any 
virus or defect transmitted by this email. ITV reserves the right to 
monitor all e mails and the systems upon which such e mails are stored or 
circulated.

This email does not conclude a binding agreement. Any views or opinions 
presented in this email are solely those of the author and do not 
necessarily represent those of ITV.

Thank You.

**Comment by sardaukar** [comment]
Hello!

I'm taking some dumps with mitmdump and saving some flows with mitmproxy,
and then opening them with the gem. However, some of the responses are GZip
encoded, and the library saves them as they are (ie, does not unpack them),
which is OK - I'm just having difficulty decompressing the streams in Ruby.
So, in a way, this is not a problem with your lib, but with me using Ruby's
Gzip stdlib implementation - but I thought you might have had this issue in
the past, since Gzip encoding for replies is quite common.

In essence, if I save them to file, I can decompress them using 'gunzip' on
the shell, but I'd like to decompress the streams with just Ruby.

Help? Thanks for the reply,

Bruno

On Mon, Aug 18, 2014 at 9:50 AM, Marc Bleeze notifications@github.com
wrote:

> Hi Bruno,
> 
> Thanks for the mail. If you provide a few more details of how you are
> using
> my gem then I can take a look, I actually suspect that the problem may
> well
> be within the libmproxy library which my code uses to read from dumps.
> 
> Cheers
> 
> Marc
> 
> On 15 August 2014 19:31, Bruno Antunes notifications@github.com wrote:
> 
> > Btw, saving them to a file and then doing
> > 
> > cat file | gunzip
> > 
> > works :/
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/marcyb/rmitm/issues/1#issuecomment-52341684.
> 
> ## 
> 
> http://www.itv.com
> 
> http://www.itv.com
> http://www.itv.com
> 
> ITV plc (Registration No. 4967001) (ITV) is incorporated in England and
> Wales with its registered office at The London Television Centre, Upper
> Ground, London SE1 9LT. Please visit the official ITV website at
> www.itv.com
> for the latest company news.
> 
> The contents of this email and any attachments are confidential, may be
> privileged, may be subject to copyright and are intended solely for the
> use
> of the individual to whom they are addressed. If you have received this
> email and you are not the intended recipient please
> notifypostmaster@itv.com
> and delete this email and you are notified that disclosing, copying,
> distributing or taking any action in reliance on the contents of this
> email
> are strictly prohibited.
> 
> Although ITV routinely screens for viruses, recipients should scan this
> email and any attachments for viruses. ITV makes no representation or
> warranty that this email or any of its attachments is free of viruses or
> defects and does not accept any responsibility for any damage caused by
> any
> virus or defect transmitted by this email. ITV reserves the right to
> monitor all e mails and the systems upon which such e mails are stored or
> circulated.
> 
> This email does not conclude a binding agreement. Any views or opinions
> presented in this email are solely those of the author and do not
> necessarily represent those of ITV.
> 
> Thank You.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcyb/rmitm/issues/1#issuecomment-52466373.

## 

Bruno Antunes
*"If we hit that bullseye, the rest of the dominoes will fall like a house
of cards. Checkmate." *- Cpt. Zapp Brannigan
about.me http://about.me/bruno.antunes
GPG key https://www.dropbox.com/s/jgnxuvox1fp3qcy/F610C1D6%20PUB.asc

**Comment by marcyb** [comment]
Hi Bruno,

I see, yes, I have had the same problem. My quick and dirty solution was to
just delete the 'Accept-Encoding' header from the client request which
ensured that the server response was uncompressed. When I have time I may
look into a better solution, probably decompressing the dump in python
before creating the Ruby JSON object. But at the moment the workaround is
sufficient to meet my needs.

Thanks

Marc

On 18 August 2014 09:57, Bruno Antunes notifications@github.com wrote:

> Hello!
> 
> I'm taking some dumps with mitmdump and saving some flows with mitmproxy,
> and then opening them with the gem. However, some of the responses are
> GZip
> encoded, and the library saves them as they are (ie, does not unpack
> them),
> which is OK - I'm just having difficulty decompressing the streams in
> Ruby.
> So, in a way, this is not a problem with your lib, but with me using
> Ruby's
> Gzip stdlib implementation - but I thought you might have had this issue
> in
> the past, since Gzip encoding for replies is quite common.
> 
> In essence, if I save them to file, I can decompress them using 'gunzip'
> on
> the shell, but I'd like to decompress the streams with just Ruby.
> 
> Help? Thanks for the reply,
> 
> Bruno
> 
> On Mon, Aug 18, 2014 at 9:50 AM, Marc Bleeze notifications@github.com
> wrote:
> 
> > Hi Bruno,
> > 
> > Thanks for the mail. If you provide a few more details of how you are
> > using
> > my gem then I can take a look, I actually suspect that the problem may
> > well
> > be within the libmproxy library which my code uses to read from dumps.
> > 
> > Cheers
> > 
> > Marc
> > 
> > On 15 August 2014 19:31, Bruno Antunes notifications@github.com
> > wrote:
> > 
> > > Btw, saving them to a file and then doing
> > > 
> > > cat file | gunzip
> > > 
> > > works :/
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/marcyb/rmitm/issues/1#issuecomment-52341684.
> > 
> > ## 
> > 
> > http://www.itv.com
> > 
> > http://www.itv.com
> > http://www.itv.com
> > 
> > ITV plc (Registration No. 4967001) (ITV) is incorporated in England and
> > Wales with its registered office at The London Television Centre, Upper
> > Ground, London SE1 9LT. Please visit the official ITV website at
> > www.itv.com
> > for the latest company news.
> > 
> > The contents of this email and any attachments are confidential, may be
> > privileged, may be subject to copyright and are intended solely for the
> > use
> > of the individual to whom they are addressed. If you have received this
> > email and you are not the intended recipient please
> > notifypostmaster@itv.com
> > and delete this email and you are notified that disclosing, copying,
> > distributing or taking any action in reliance on the contents of this
> > email
> > are strictly prohibited.
> > 
> > Although ITV routinely screens for viruses, recipients should scan this
> > email and any attachments for viruses. ITV makes no representation or
> > warranty that this email or any of its attachments is free of viruses or
> > defects and does not accept any responsibility for any damage caused by
> > any
> > virus or defect transmitted by this email. ITV reserves the right to
> > monitor all e mails and the systems upon which such e mails are stored
> > or
> > circulated.
> > 
> > This email does not conclude a binding agreement. Any views or opinions
> > presented in this email are solely those of the author and do not
> > necessarily represent those of ITV.
> > 
> > Thank You.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/marcyb/rmitm/issues/1#issuecomment-52466373.
> 
> ## 
> 
> Bruno Antunes
> *"If we hit that bullseye, the rest of the dominoes will fall like a house
> of cards. Checkmate." *- Cpt. Zapp Brannigan
> about.me http://about.me/bruno.antunes
> GPG key https://www.dropbox.com/s/jgnxuvox1fp3qcy/F610C1D6%20PUB.asc
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/marcyb/rmitm/issues/1#issuecomment-52467009.

## 

 http://www.itv.com

http://www.itv.com
http://www.itv.com

ITV plc (Registration No. 4967001) (ITV) is incorporated in England and 
Wales with its registered office at The London Television Centre, Upper 
Ground, London SE1 9LT. Please visit the official ITV website at www.itv.com 
for the latest company news.

The contents of this email and any attachments are confidential, may be 
privileged, may be subject to copyright and are intended solely for the use 
of the individual to whom they are addressed. If you have received this 
email and you are not the intended recipient please notifypostmaster@itv.com 
and delete this email and you are notified that disclosing, copying, 
distributing or taking any action in reliance on the contents of this email 
are strictly prohibited.

Although ITV routinely screens for viruses, recipients should scan this 
email and any attachments for viruses. ITV makes no representation or 
warranty that this email or any of its attachments is free of viruses or 
defects and does not accept any responsibility for any damage caused by any 
virus or defect transmitted by this email. ITV reserves the right to 
monitor all e mails and the systems upon which such e mails are stored or 
circulated.

This email does not conclude a binding agreement. Any views or opinions 
presented in this email are solely those of the author and do not 
necessarily represent those of ITV.

Thank You.
